server:
  port: 8090
spring:
  application:
    name: dubbo-hmily-consumer
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.switchvov.dubbo.hmily.consumer
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181